### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by badjoras7** [spinach/FantasyPremierLeague-Api.py#1]
File "playersPickedInLeague.py", line 133
    except Exception, e:
                    ^
SyntaxError: invalid syntax

**Comment by spinach** [comment]
Hey @badjoras7, 

This is probably because you're using Python 3 and the script is using Python 2.7. The issue has been stated [here](https://stackoverflow.com/a/14909016/905425) and a solution is [here](https://stackoverflow.com/a/12519594/905425).
