### ISSUE TITLE
KeyError: 'elements'

### ISSUE THREAD

**Issue by dedostorpes** [spinach/FantasyPremierLeague-Api.py#11]
Hey there,

I've tried with both Python 2 & Python 3 and when I run the command as indicated in the Readme file I receive the following error:

```
Traceback (most recent call last):
  File "playersPickedInLeague.py", line 87, in <module>
    for element in allPlayers["elements"]:
KeyError: 'elements'
```

Appreciate your help and many thanks for developing it!

**Comment by spinach** [comment]
Seems they changed the url yet again, from:
 
https://fantasy.premierleague.com/api/bootstrap-static

to

https://fantasy.premierleague.com/api/bootstrap-static/

(Just the slash in the end). Try to change the url and it might solve the issue

**Comment by yathomasi** [comment]
I fixed those ones and applied for pull request
But One issue still persists 
I am creating new issue for that

**Comment by yathomasi** [comment]
@spinach  @dedostorpes  this issue is also fixed by [pull request 12](https://github.com/spinach/FantasyPremierLeague.py/pull/12) for python2 version and [pull request 14](https://github.com/spinach/FantasyPremierLeague.py/pull/14) for python3 version.
Check that out.

**Comment by spinach** [comment]
Fixed thanks to @yathomasi !
