### ISSUE TITLE
SSL error?

### ISSUE THREAD

**Issue by nyarenbee** [spinach/FantasyPremierLeague-Api.py#2]
Got SSL Error while running the script fom MAC; Any idea:
```~ python playersPickedInLeague.py -l 336217 -g 2 -t classic
Traceback (most recent call last):
  File "playersPickedInLeague.py", line 82, in <module>
    getPlayersInfo()
  File "playersPickedInLeague.py", line 20, in getPlayersInfo
    r = requests.get(PLAYERS_INFO_URL, verify=False)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='fantasy.premierleague.com', port=443): Max retries exceeded with url: /drf/bootstrap-static (Caused by SSLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)'),))
~ 
```

**Comment by spinach** [comment]
Does it always gives you this error even if you retry multiple times? Did it ever work before?
Check this SO issue, it might be helpful https://stackoverflow.com/a/24899222/905425

The script works on my side with no problem (just tried it). It seems more of a Connection / Environment Python problem, and not related to this library, so I suggest you google the error and try to find an answer in SO 😄

**Comment by spinach** [comment]
You can re-open the issue if you have more questions

**Comment by spinach** [comment]
After investigating more, it seems it is an SSL problem. Fantasy PL website seem to have updated their minimum SSL connection requirements. 

In your terminal, run `python -c "import ssl; print ssl.OPENSSL_VERSION"`. If you get 0.9.8 and not 1.0.1, then you need to upgrade the ssl version used by Python. You can google/SO to find how to do it

**Comment by spinach** [comment]
So I checked that it worked in Python 3 as it uses the correct OpenSSL version. So you can follow the instructions in the branch [python3](https://github.com/spinach/FantasyPremierLeague-Api.py/tree/python3). Just tested it, it works.
