### ISSUE TITLE
SyntaxError: invalid syntax with print str(e)

### ISSUE THREAD

**Issue by CajitaFeliz** [spinach/FantasyPremierLeague-Api.py#4]
I'm using Python 3 and I get the following problem

File "playersPickedInLeague.py", line 134
print str(e)
^
SyntaxError: invalid syntax

**Comment by spinach** [comment]
check this issue #1 for the solution

**Comment by ghost** [comment]
I viewed the solution #1 for the solution, but regarding print str(e) SyntaxError: invalid syntax, I couldnt find a solution on stack link on #1
