### ISSUE TITLE
API changes

### ISSUE THREAD

**Issue by mikeandrewjeski** [spinach/FantasyPremierLeague-Api.py#7]
Hi mate, thanks for this code. I've used it for a while now with plotly & bokeh. Just wanted to mention (in case you weren't aware) the API has changed.  At the minute, the classic league URL looks like this: 
https://fantasy.premierleague.com/api/leagues-classic/10529/standings/?page_new_entries=1&page_standings=1

and the H2H URL:
https://fantasy.premierleague.com/api/leagues-h2h/213672/standings/?page_new_entries=1&page_standings=1

hope this helps.

**Comment by spinach** [comment]
Hey @mikeandrewjeski ,

Indeed you are right, I updated my [SO answer](https://stackoverflow.com/a/38937896/905425) but forgot to do it here. Thanks for pointing it out mate!

**Comment by yathomasi** [comment]
Hey I have changed those accordingly and submitted for pull request. Check that out.

**Comment by spinach** [comment]
Thanks @yathomasi for submitting the fix, really appreciated! I just merged both branches in #8 #9
